{
 "title": "Pizza Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(get_request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(delete_request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(put_request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(post_request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(total_request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Regular Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(request_latency_delay{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "request latency"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "rate(pizza_latency_delay{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "pizza latency"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_count{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "B{{label_name}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "active_users_count{source=\"jwt-pizza-service\"}",
     "legendFormat": "active users"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(failed_auth_count{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "failed auth"
    },
    {
     "expr": "rate(success_auth_count{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "success auth"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(failed_purchases_count{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "failed purchases"
    },
    {
     "expr": "rate(pizza_purchases_count{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "pizzas purchases"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_usage{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_usage{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  }
 ]
}